### PR TITLE
Support `--adapt-slug` to override the default directory when installing zips

### PR DESCRIPTION
**Pull request by borkweb**
The `install` subcommand for both plugins and themes now support the following:

* `wp [plugin|theme] install whatever.zip --adapt-slug=bork` - When installing a zip (whether remote or local), the directory it gets installed to will be the value in `adapt-slug`; in this case, `bork/`'
* `wp [plugin|theme] install whatever.zip --adapt-slug` - When installing a zip (whether remote or local), the plugin or theme name will be fetched from the bootstrap file or style.css respectively, slug-ify it, and then use that as the directory it gets installed to.

Fixes: #74

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@borkweb Looks pretty great so far! I kicked off the test suite to see if there are any side effects.

What do you think should happen for `wp [plugin|theme] install whatever.zip whatever2.zip --adapt-slug=bork`? Should we throw an error?

**Comment by borkweb** [comment]
@danielbachhuber - Oh! I that's a great question. Erroring makes a lot of sense.

**Comment by danielbachhuber** [comment]
@borkweb Sounds good. Can you add a test case for that scenario? It looks like there's a coding standards issue that needs to be fixed too.

**Comment by danielbachhuber** [comment]
Proceeding with https://github.com/wp-cli/wp-cli/issues/5594 for this repository. I've captured this PR to https://gist.github.com/danielbachhuber/6d013dbff6c939165c4c03c34b6477a1 in case this PR is auto-closed or broken in some way.

**Pull request closed without merging**
