### PR TITLE
Add title/description for mu-plugins.

### PR DESCRIPTION
**Pull request by alexstine**
Currently, only name is populated for mu-plugins. This PR will also fill in the title and add the description.

### CODE REVIEW

**Comment by schlessera** [comment]
Thanks for the PR, @alexstine !

The code looks good at first glance, but to merge it, we'd need a Behat test as well to ensure it actually does (and keeps doing) what it is supposed to do. Do you care to add such a test?

**Comment by alexstine** [comment]
@schlessera Can you find another contributor to implement the test? I just don't have time at the moment and I'm sure you are probably in the same boat. Maybe one for next CLI meeting?

Thanks.

**Comment by wojsmol** [comment]
@alexstine Changes reverted in https://github.com/wp-cli/extension-command/pull/305/commits/10b75d3255ab349541d51965564d7bb04f3964bf was correct.

**Comment by alexstine** [comment]
@wojsmol Better now? Just refreshed the fork/branch.

**Comment by wojsmol** [comment]
@alexstine LGTM now. Tests are requiring @schlessera  approval to run.

**Comment by alexstine** [comment]
@wojsmol These check fails don't look related to my changes. Maybe worth a re-run?

**Comment by swissspidy** [comment]
Should we also add support for descriptions?

Tests are all passing now btw

**Comment by alexstine** [comment]
Nothing like all green checks. 👍 

If you think it is a good idea, I can try to get descriptions working or can handle in another PR.

**Comment by swissspidy** [comment]
If you're up for it, that would be great. Can be in this PR or a new one, whatever works best for you. Code-wise it should be mostly copy & paste

**Comment by alexstine** [comment]
@swissspidy Done. Not sure if the tests will pass but hopefully so. Gave this a test on my test server, seems solid enough.

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
