### PR TITLE
Support multiple values on "plugin list --status=X" #194

### PR DESCRIPTION
**Pull request by xyulex**
Added support for multiple values in plugin list --status (e.g. wp plugin list --status=active,inactive"

### CODE REVIEW

**Comment by xyulex** [comment]
@schlessera  Travis CI is returning some errors. I launched the behat in my computer and they return the same errors in the original repo. Am I missing something?

**Comment by xyulex** [comment]
@schlessera Can I get some support on it?

**Comment by schlessera** [comment]
@xyulex You're logic seems to be off.

First of all, you're replacing the initial logic, instead of adding to it. So while you're trying to add this status filtering, you're breaking the rest of the fields.

Also, after your `explode()`, you should do something like this for deciding when to remove:
```php
if ( ! in_array( $assoc_args[ 'status' ], $statuses, true ) ) {
	unset( $all_items[ $key ];
}
```

Does that make sense?

**Comment by xyulex** [comment]
@schlessera I already did that change in that commit: https://github.com/wp-cli/extension-command/pull/199/commits/edcf08caea4f5f2a92eaf3090e6e5cc0598a3a18

**Comment by schlessera** [comment]
@xyulex No, this is not what I'm referring to. This is the total change so far in this PR:
Image 2019-11-14 at 3 15 20 PM

As you can see, the entire logic is only executed if it encounters the `status` field. For any other field, where it would previously `unset()` the ones that weren' matching, it does not do anything anymore.

You replaced the logic for handling all fields with the logic for handling the status field only.

**Comment by schlessera** [comment]
Thanks for all the effort, @xyulex!

This was fixed via #234

**Pull request closed without merging**
