### PR TITLE
Fix: correctly deactivate network activated plugin before uninstall.

### LINKED ISSUE #312: Uninstall with deactivate flag
```
user@server:/data/blogs$ wp plugin uninstall google-analyticator --deactivate
Deactivating 'google-analyticator'...
Warning: Plugin 'google-analyticator' is network active and must be deactivated with --network flag.
Uninstalled and deleted 'google-analyticator' plugin.
Success: Uninstalled 1 of 1 plugins.
```
Despite the warning that a plugin was network active and **must be** deactivated with the --network flag, the plugin was in fact deleted. No skin off my nose, but it seems contradictory or unintended, based on the warning message.

### PR DESCRIPTION
**Pull request by NielsdeBlaauw**
When uninstalling a network activated plugin, the network tag is now added to correctly deactivate the plugin before removal.

Fixes #312

### CODE REVIEW

**Comment by Sidsector9** [comment]
@NielsdeBlaauw it looks good to me, however the functional tests are failing. Can you please look into it?
Let me know if you need any help, thanks!

**Comment by Sidsector9** [comment]
@NielsdeBlaauw thank you for your contribution! It looks good to me, however the functional tests are failing. Can you please look into it?
Let me know if you need any help, thanks!

**Comment by janw-me** [comment]
Code looks good. Only needs tests.
I recommend taking a look here https://github.com/wp-cli/super-admin-command/blob/main/features/super-admin.feature
For testing with a multisite.
Also let us know if you need help.

**Comment by janw-me** [comment]
The code looks good. It should have a test to cover this specific usage with a multisite.
I recommend taking a look [here](https://github.com/wp-cli/super-admin-command/blob/main/features/super-admin.feature) to write tests with a multisite setup.

If you need help give a shout.

**Comment by danielbachhuber** [comment]
Proceeding with https://github.com/wp-cli/wp-cli/issues/5594 for this repository. I've captured this PR to https://gist.github.com/danielbachhuber/f9aa4f759c7d57ff2663d07766241692 in case this PR is auto-closed or broken in some way.

**Pull request closed without merging**
