### PR TITLE
Replace one-time-login with a sample plugin in the tests

### LINKED ISSUE #301: Fix: failing tests "Branch names should be removed from Github projects" on PHP 5.6
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

First reported in https://github.com/wp-cli/extension-command/pull/300#issuecomment-938755216, The behat tests are failing in WordPress 5.6 because the plugin [one-time-login](https://github.com/danielbachhuber/one-time-login/blob/64398c491c8a16efe9adfc3b1497d3845d464a25/one-time-login.php#L79) is being downloaded in the tests which requires PHP 7.1

**Describe how other contributors can replicate this bug**

- Check any GitHub action "Testing" on PHP 5.6 ([example](https://github.com/wp-cli/extension-command/pull/300/checks?check_run_id=3840427437#step:13:64))

**Describe what you would expect as the correct outcome**
No failing tests.

**Provide a possible solution**

A simple repo, preferably in wp-cli organisation with just the plugin header can be used in the tests so that this error will not happen in future.

### PR DESCRIPTION
**Pull request by Nikschavan**
Fixes #301

Replaces the plugin [one-time-login](https://github.com/danielbachhuber/one-time-login/) with a [sample WordPress plugin](https://github.com/Nikschavan/test-wordpress-plugin)

### CODE REVIEW

**Comment by swissspidy** [comment]
@schlessera Should this sample plugin live in the wp-cli org so that we can guarantee it exists? In case https://github.com/Nikschavan/test-wordpress-plugin ever gets deleted :-)

**Comment by Nikschavan** [comment]
I was hoping it would be simpler to fork and get this into wp-cli org? I mentioned in the issue #301 it would be preferable to be in this org.

Maybe anyone with capabilities can create a repo here instead and I can use that links in this PR?

**Comment by wojsmol** [comment]
We have https://github.com/wp-cli-test/generic-example-pluginor AFAIK we can transfer @Nikschavan to `wp-cli-test` organisation.

**Comment by schlessera** [comment]
@Nikschavan This is done, the repo now has two published releases, each with a separate ZIP as attached asset.

**Pull request merged**
